# Generated by Django 3.0.8 on 2020-07-26 18:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200727_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[700, 400], upload_to='images'),
        ),
    ]
