# Generated by Django 3.0.8 on 2020-07-26 18:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200727_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=99, size=[700, 400], upload_to='images'),
        ),
    ]
