# Generated by Django 3.0.8 on 2020-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.CharField(choices=[('zero', 'Zero'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('both', 'Both')], default='both', max_length=20, null=True),
        ),
    ]
